version = 0.1

[default.deploy.parameters]
stack_name = "visitjo-restored-stack"
resolve_s3 = true
s3_prefix = "visitjo-restored-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "OpenAISecretArn=\"\""
image_repositories = []
disable_rollback = true

[default.global.parameters]
region = "us-east-1"
